# Generated by Django 4.0 on 2021-12-29 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practical_20', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
